### PR TITLE
Gruntify

### LINKED ISSUE #20: Port existing build tasks to Grunt
- Minify/package for download
- JSHint
- Watch task
- Run unit tests (Which aren't at all automated right now)
- Documentation. The documentation is already started as JSDoc. 
- Publish demos and documentation to gh-pages

### PR DESCRIPTION
**Pull request by bobholt**
Fixes #20. Broken into 3 commits in case you want to break this up:
- Replicate existing ANT tasks (probably should have been more atomic ¯_(ツ)_/¯)
- Add Jasmine Automation
- Add gh-pages task

Basics: 
1. Clone
2. `npm install -g grunt-cli`
3. `npm install`

Runt `grunt --help` to see all tasks. Basics, though:
- `grunt` - alias for `grunt dev` - runs lint, tests, and starts watch task
- `grunt dist` - does the above (minus watch), copies Cee.js to root, minifies to root, builds documentation, duplicates all of that work into gh-pages, and pushes gh-pages to GitHub.

The gh-pages branch looked pretty different from the master branch - even the index.html file, so I created a gh-pages directory that has the reflects the current state. The `dist` task keeps this directory in sync with the main repo. The gh-pages task pushes this directory (and only this directory) to your origin/gh-pages branch. Note this is automatic. If you run `grunt dist` your origin/gh-pages branch on GitHub WILL be overwritten.

I'd rather see the master branch have everything that needs to go in gh-pages, and just duplicate the repo there, but you may disagree. We can make a different issue for that. It would eliminate the need to duplicate the clean, copy, uglify, rename, and jsdoc tasks for both `./` and `gh-pages/`

### CODE REVIEW

**Comment by roblarsen** [comment]
The branches are so different as a simple legacy of the way that the gh-pages branch is generated and it just lived on from there. I see zero reason why they can't be the same. It's just the index.html and associated web files.

**Comment by bobholt** [comment]
Ok, a quick update to that PR, then!

**Comment by bobholt** [comment]
Updated (and force-pushed to update the PR). You can see what automatically goes to the gh-pages on my origin/gh-pages: https://bobholt.github.io/CanvasJS/

**Comment by roblarsen** [comment]
Looks great. I excluded node_modules from the copy because... forever and I might go in and tweak some other files to clean up the output branch, but all in all- awesome.

**Comment by bobholt** [comment]
Oh yeah, good call.

**Pull request merged**
